Add DddDbContext
codehardth/Codehard.Common pull request #103
Opened 2024-07-01 10:10 UTC by rungwiroon

2024-07-15 04:15 UTC, Desz01ate requested changes

2024-07-15 04:15 UTC, Desz01ate commented on src/Codehard.Infrastructure/Codehard.Infrastructure.EntityFramework/DbContexts/DddDbContext.cs
> +
convention ดูไม่เหมือนเพื่อน ๆ ที่เหลือนะครับ

2024-09-18 09:17 UTC, rungwiroon commented on src/Codehard.Infrastructure/Codehard.Infrastructure.EntityFramework/DbContexts/DddDbContext.cs
> +
แก้ล่ะครับ

2024-09-19 08:26 UTC, Desz01ate approved these changes

2024-09-23 03:21 UTC, merged