Add infrastructure projects for Entity Framework
codehardth/Codehard.Common pull request #32
Opened 2023-01-30 09:09 UTC by Desz01ate

2023-01-30 10:34 UTC, rungwiroon approved these changes

2023-01-31 05:26 UTC, rungwiroon approved these changes

2023-01-31 05:26 UTC, rungwiroon commented on src/Codehard.Infrastructure/Codehard.Infrastructure.EntityFramework/Codehard.Infrastructure.EntityFramework.csproj
> +      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.2" />
ใช่เวอร์ชั่น 7 เหรอ?

2023-01-31 07:18 UTC, rungwiroon requested changes

2023-01-31 07:18 UTC, rungwiroon commented on src/Codehard.Infrastructure/Codehard.Infrastructure.EntityFramework/Interfaces/IPaginatedQuery.cs
> +public interface IPaginatedQuery<out T> : IReadOnlyList<T>
ชื่อ PaginatedQuery ความหมายไม่ค่อยตรงนะ

2023-01-31 07:41 UTC, Desz01ate commented on src/Codehard.Infrastructure/Codehard.Infrastructure.EntityFramework/Interfaces/IPaginatedQuery.cs
> +public interface IPaginatedQuery<out T> : IReadOnlyList<T>
Fixed.

2023-01-31 07:56 UTC, rungwiroon approved these changes

2023-01-31 08:12 UTC, merged