Redesign error result ASP.NET
codehardth/Codehard.Common pull request #51
Opened 2023-04-03 04:17 UTC by rungwiroon

2023-04-04 11:34 UTC, gfhdlcod02 approved these changes

2023-04-04 14:58 UTC, rungwiroon commented on src/Codehard.Functional/Codehard.Functional.AspNetCore/Commons.cs
> +                    HttpResultError when @override =>
แก้แล้วๆ

2023-04-05 04:41 UTC, Desz01ate commented on src/Codehard.Functional/Codehard.Functional.AspNetCore/Commons.cs
> +
เบิ้ลครับ

2023-04-12 03:04 UTC, Desz01ate requested changes

2023-04-12 03:04 UTC, Desz01ate commented on src/Codehard.Functional/Codehard.Functional.AspNetCore/ErrorWrapperActionResult.cs
> +        if (context == null)
ใช้ [ArgumentNullException.ThrowIfNull](https://learn.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull?view=net-6.0) แทนได้ไหมครับ

2023-04-12 03:04 UTC, Desz01ate commented on src/Codehard.Functional/Codehard.Functional.AspNetCore/ErrorWrapperActionResult.cs
> +        if (context == null)
ว่าแต่ `ActionContext` เอง ไม่ได้เป็น nullable มันมีโอกาสเป็น null จริง ๆ หรือเปล่าครับ

2023-04-12 10:14 UTC, rungwiroon commented on src/Codehard.Functional/Codehard.Functional.AspNetCore/ErrorWrapperActionResult.cs
> +        if (context == null)
นั่นสิ เอา null guard ออกไปเลยดีไหม

2023-04-12 10:33 UTC, Desz01ate commented on src/Codehard.Functional/Codehard.Functional.AspNetCore/ErrorWrapperActionResult.cs
> +        if (context == null)
คิดว่าน่าจะไม่จำเป็นต้อง guard ครับ เอาออกก็ได้ครับ

2023-04-12 20:37 UTC, merged