Add more Eff extensions
codehardth/Codehard.Common pull request #65
Opened 2023-07-25 10:22 UTC by rungwiroon

2023-07-26 04:13 UTC, Desz01ate requested changes

2023-07-26 04:13 UTC, Desz01ate commented on src/Codehard.Functional/Codehard.Functional/EffectExtensions.cs
> +        => ma.Bind(
เรียกใช้ overload ข้างบนเลยก็ได้นะครับ

2023-07-26 07:50 UTC, rungwiroon commented on src/Codehard.Functional/Codehard.Functional/EffectExtensions.cs
> +        => ma.Bind(
แก้เป็นข้างบนเรียกใช้ตรงนี้แทนครับ

2023-08-02 08:47 UTC, Desz01ate approved these changes
LGTM

2023-08-02 08:52 UTC, merged